
name: ml-in-production workflow

on:
  push:
    branches:
      - main
    paths:
      - 'new-ml-in-production/**'

  pull_request:
    branches:
      - main
    paths:
      - 'new-ml-in-production/**'

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.7'

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true

    - name: Load cached venv
      uses: actions/cache@v4
      id: cache-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('new-ml-in-production/poetry.lock') }}

    - name: Install dependencies using poetry
      if: steps.cache-poetry-dependencies.outputs.cache-hit != 'true'
      run: 
        cd new-ml-in-production;
        poetry run make install;

    - name: Run lint with ruff
      run: 
        cd new-ml-in-production;
        poetry run make check;

       

